version: "3.9"

services:
  deepstreem_resnet:
    build:
      context: .
      dockerfile: Dockerfile
#    command: ["./deepstream-test5-analytics", "-c", "config/dstest_occupancy_analytics.txt"]
    command: ["python3", "-m", "http.server"]
    ports:
      - "8012:8000"
#      - "3030:3030"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - KAFKA_HOST=kafka1-deepstreem_resnet
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=quickstart-events
      - KAFKA_GROUP_ID=0
      - DISPLAY=:1
    volumes:
      - './input/:/input/'
      - './output/:/output/'
      - /tmp/.X11-unix/:/tmp/.X11-unix
    runtime: nvidia
    networks:
      - arch-network
    depends_on:
      - kafka1-deepstreem_resnet
#      - kafka2-deepstreem_resnet
#      - consumer-deepstreem_resnet
      - kafka-ui-deepstreem_resnet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    networks:
      - arch-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka1-deepstreem_resnet:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    networks:
      - arch-network
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1-deepstreem_resnet:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui-deepstreem_resnet:
      image: provectuslabs/kafka-ui:v0.4.0
      ports:
        - "8777:8080"
      environment:
        KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka1-deepstreem_resnet:9092"
        KAFKA_CLUSTERS_0_NAME: "kraft"
      networks:
        - arch-network

  consumer-deepstreem_resnet:
    build:
#      context: consumer
      context: consumer-java
      dockerfile: Dockerfile
    container_name: consumer-deepstreem_resnet
    restart: always
    environment:
      - KAFKA_HOST=kafka1-deepstreem_resnet
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=quickstart-events
      - KAFKA_GROUP_ID=0
    networks:
      - arch-network
    depends_on:
      - kafka1-deepstreem_resnet
#      - kafka2-deepstreem_resnet

networks:
  arch-network:
    driver: "bridge"

volumes:
  kafka_volume1ds:
  kafka_volume2ds: